// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0pYoXsiKwStNAD1lALP5FsLWldnsNLn0',
    appId: '1:214829073736:web:9892ed90e58e604ad85f7d',
    messagingSenderId: '214829073736',
    projectId: 'perfume-41808',
    authDomain: 'perfume-41808.firebaseapp.com',
    storageBucket: 'perfume-41808.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBf3AaqXwcnwwxJgBhbba45jVP8QmSpEP0',
    appId: '1:214829073736:android:1449a6783b5eb417d85f7d',
    messagingSenderId: '214829073736',
    projectId: 'perfume-41808',
    storageBucket: 'perfume-41808.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDt9qK9WEEDL6LZT7MPt_GB54udgaFQwnY',
    appId: '1:214829073736:ios:0dc9e9716f59a9e3d85f7d',
    messagingSenderId: '214829073736',
    projectId: 'perfume-41808',
    storageBucket: 'perfume-41808.firebasestorage.app',
    iosBundleId: 'com.example.januaryProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDt9qK9WEEDL6LZT7MPt_GB54udgaFQwnY',
    appId: '1:214829073736:ios:0dc9e9716f59a9e3d85f7d',
    messagingSenderId: '214829073736',
    projectId: 'perfume-41808',
    storageBucket: 'perfume-41808.firebasestorage.app',
    iosBundleId: 'com.example.januaryProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0pYoXsiKwStNAD1lALP5FsLWldnsNLn0',
    appId: '1:214829073736:web:4f834cc95687c925d85f7d',
    messagingSenderId: '214829073736',
    projectId: 'perfume-41808',
    authDomain: 'perfume-41808.firebaseapp.com',
    storageBucket: 'perfume-41808.firebasestorage.app',
  );
}
