name: january_project
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  lottie: ^3.3.2
  carousel_slider: ^5.1.1
  salomon_bottom_bar: ^3.3.2
  provider: ^6.1.5+1

  # 🔥 Firebase (نسخ متوافقة مع بعض)
  firebase_core: ^4.5.0
  firebase_auth: ^6.2.0
  cloud_firestore: ^6.1.3
  google_sign_in: 6.3.0
  firebase_storage: ^13.1.0
  image_picker: ^1.0.7
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Averia
      fonts:
        - asset: assets/fonts/Averia.ttf
          style: italic